import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/components/providers";
import Header from "@/components/ui/header";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('flex min-h-screen flex-col antialiased')}>
        <Providers>
          <Header/>
          <main className="grow">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
